name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in hiyoung posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 10
          committer_username: "hiyoung123"
          committer_email: "hiyoungliu@gmail.com"
          feed_list: "https://feed.cnblogs.com/blog/u/462568/rss/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$date] [$title]($url)  $newline"
